version: '3.2'

services:
    php:
        #image: campbellsoftwaresolutions/osticket
        build: .
        #volumes:
        #    - .:/data/upload
        networks:
            - code-network
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
            - MYSQL_DATABASE=osticket
            - MYSQL_PASSWORD=secret
            - MYSQL_USER=osticket
        ports:
            - 8080:80
    db:
        image: mysql:5.7
       
        volumes:
            - ./mysqldata:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
            - MYSQL_DATABASE=osticket
            - MYSQL_PASSWORD=secret
            - MYSQL_USER=osticket
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
